name: Notion2Github
author: Younho Choo
description: Automatic syncronization from Notion to Github
branding:
  icon: inbox
  color: black
inputs:
  database-url:
    description: URL of the notion database to extract.
    required: true

  # export config
  docs-directory:
    description: Directory in which the notion page to extract will be stored.
    required: false
  recursive-export:
    description: Whether or not to recursively export child page.
    required: false
    default: true
  create-page-directory:
    description: Whether or not to create subdirectory with page title.
    required: false
    default: true
  add-metadata:
    description: Whether or not to add metadata to content.
    required: false
    default: false
  lower-pathname:
    description: Whether or not to make pathname to lowercase.
    required: false
    default: false
  lower-filename:
    description: Whether or not to make pathname to uppercase.
    required: false
    default: false
  line-break:
    description: Whether or not to convert empty blocks of notion to line break tag(<br />).
    required: false
    default: false

  # database-config
  category-column-name:
    description: >
      In the Notion database, you can categorize content by category with "Select" property.
      If you create a "Select" property in the Notion database and pass the name of the column,
      then folders will be created by category.
    required: false
  tags-column-name:
    description: >
      In the Notion database, you can tag content with "Multi Select" property. (should set add_metadata to True.)
      If you create a "Multi Select" property in the Notion database and pass the name of the column,
      then meta data will be insterted to contents.
    required: false
  created-time-column-name:
    description: >
      In the Notion database, you can manage created time of content with "Created Time" property.
      If you create a "Created Time" property in the Notion database and pass the name of the column,
      you can add created time to filename.
    required: false
  status-column-name:
    description: >
      In the Notion database, you can manage the status of content with "Select" property.
      If you create a "Select" property in the Notion database and pass the name of the column,
      you can import contents in a specific state or change the status of the content.
    required: false
  current-status:
    description: Status of content to import. Must be an option in the "status_column_name" column.
    required: false
  next-status:
    description: Status of contents after content was imported. Must be an option in the "status_column_name" column.
    required: false
  filters:
    description: Key, value pair of filter list to apply to the Notion database.
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.database-url }}
    - --docs-directory
    - "${{ inputs.docs-directory }}"
    - --recursive-export
    - "${{ inputs.recursive-export }}"
    - --create-page-directory
    - "${{ inputs.create-page-directory }}"
    - --add-metadata
    - "${{ inputs.add-metadata }}"
    - --lower-pathname
    - "${{ inputs.lower-pathname }}"
    - --lower-filename
    - "${{ inputs.lower-filename }}"
    - --line-break
    - "${{ inputs.line-break }}"
    - --category-column-name
    - "${{ inputs.category-column-name }}"
    - --tags-column-name
    - "${{ inputs.tags-column-name }}"
    - --created-time-column-name
    - "${{ inputs.created-time-column-name }}"
    - --status-column-name
    - "${{ inputs.status-column-name }}"
    - --current-status
    - "${{ inputs.current-status }}"
    - --next-status
    - "${{ inputs.next-status }}"
    - --filters
    - "${{ inputs.filters }}"
