name: Notion2Github
author: Younho Choo
description: Automatic syncronization from Notion to Github
branding:
  icon: inbox
  color: black
inputs:
  database-url:
    description: URL of the notion database to extract.
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --url
    - ${{ inputs.database-url }}
    - --is-database
